In [12]:
# ==========================================
# STEP 1: Import Required Libraries
# ==========================================

import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder

print("✅ All libraries imported successfully!")

✅ All libraries imported successfully!

In [2]:
# ==========================================
# STEP 2: Load Dataset
# ==========================================

df = pd.read_excel("../Data/fraud_dataset.xlsx")

print("✅ Dataset Loaded Successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

✅ Dataset Loaded Successfully!
Rows: 10000
Columns: 14

,Transaction_ID,Customer_ID,Age,Gender,Product_Category,Amount,Payment_Method,Device,Browser,Country,IP_Address,Transaction_Time,Shipping_Address_Match,Is_Fraud
0,T000001,C00785,42,Male,Books,28633.39,COD,Tablet,Edge,Singapore,102.248.8.136,2025-01-13 23:34:00,No,0
1,T000002,C00981,46,Female,Electronics,15707.87,COD,Desktop,Chrome,Canada,202.139.23.128,2025-07-26 11:12:00,Yes,0
2,T000003,C02554,22,Male,Groceries,29847.79,Credit Card,Mobile,Chrome,Canada,5.63.106.60,2025-06-19 04:46:00,Yes,0
3,T000004,C00197,69,Male,Sports,6357.38,UPI,Tablet,Chrome,Canada,9.239.83.9,2025-05-08 12:09:00,No,1
4,T000005,C00082,37,Female,Electronics,44753.01,Net Banking,Mobile,Chrome,UK,160.87.49.112,2025-11-27 14:29:00,No,0

In [3]:
# ==========================================
# STEP 3: Dataset Information
# ==========================================

print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Transaction_ID          10000 non-null  str
 1   Customer_ID             10000 non-null  str
 2   Age                     10000 non-null  int64
 3   Gender                  10000 non-null  str
 4   Product_Category        10000 non-null  str
 5   Amount                  10000 non-null  float64
 6   Payment_Method          10000 non-null  str
 7   Device                  10000 non-null  str
 8   Browser                 10000 non-null  str
 9   Country                 10000 non-null  str
 10  IP_Address              10000 non-null  str
 11  Transaction_Time        10000 non-null  str
 12  Shipping_Address_Match  10000 non-null  str
 13  Is_Fraud                10000 non-null  int64
dtypes: float64(1), int64(2), str(11)
memory usage: 1.9 MB
None

In [4]:
# ==========================================
# STEP 4: Check Missing Values
# ==========================================

print("Missing Values")
print(df.isnull().sum())

Missing Values
Transaction_ID            0
Customer_ID               0
Age                       0
Gender                    0
Product_Category          0
Amount                    0
Payment_Method            0
Device                    0
Browser                   0
Country                   0
IP_Address                0
Transaction_Time          0
Shipping_Address_Match    0
Is_Fraud                  0
dtype: int64

In [5]:
# ==========================================
# STEP 5: Check and Remove Duplicate Rows
# ==========================================

print("Duplicate Rows Before:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicate Rows After:", df.duplicated().sum())
print("Current Dataset Shape:", df.shape)

Duplicate Rows Before: 0
Duplicate Rows After: 0
Current Dataset Shape: (10000, 14)

In [6]:
# ==========================================
# STEP 6: Convert Transaction_Time
# ==========================================

df["Transaction_Time"] = pd.to_datetime(df["Transaction_Time"])

print("✅ Transaction_Time converted successfully!")
print(df["Transaction_Time"].head())

✅ Transaction_Time converted successfully!
0   2025-01-13 23:34:00
1   2025-07-26 11:12:00
2   2025-06-19 04:46:00
3   2025-05-08 12:09:00
4   2025-11-27 14:29:00
Name: Transaction_Time, dtype: datetime64[us]

In [7]:
# ==========================================
# STEP 7: Feature Engineering
# ==========================================

df["Transaction_Hour"] = df["Transaction_Time"].dt.hour
df["Transaction_Day"] = df["Transaction_Time"].dt.day
df["Transaction_Month"] = df["Transaction_Time"].dt.month

print("✅ New Features Created!")
df[["Transaction_Hour","Transaction_Day","Transaction_Month"]].head()

✅ New Features Created!

   Transaction_Hour  Transaction_Day  Transaction_Month
0                23               13                  1
1                11               26                  7
2                 4               19                  6
3                12                8                  5
4                14               27                 11

In [8]:
# ==========================================
# STEP 8: Label Encoding
# ==========================================

label_encoder = LabelEncoder()

categorical_columns = [
    "Transaction_ID",
    "Customer_ID",
    "Gender",
    "Product_Category",
    "Payment_Method",
    "Device",
    "Browser",
    "Country",
    "IP_Address",
    "Shipping_Address_Match"
]

for column in categorical_columns:
    df[column] = label_encoder.fit_transform(df[column])

print("✅ Label Encoding Completed!")

✅ Label Encoding Completed!

In [9]:
# ==========================================
# STEP 9: Drop Original Transaction_Time
# ==========================================

df.drop("Transaction_Time", axis=1, inplace=True)

print("Remaining Columns:")
print(df.columns)

Remaining Columns:
Index(['Transaction_ID', 'Customer_ID', 'Age', 'Gender', 'Product_Category',
       'Amount', 'Payment_Method', 'Device', 'Browser', 'Country',
       'IP_Address', 'Shipping_Address_Match', 'Is_Fraud', 'Transaction_Hour',
       'Transaction_Day', 'Transaction_Month'],
      dtype='str')

In [10]:
# ==========================================
# STEP 10: Save Processed Dataset
# ==========================================

df.to_excel("../Data/processed_fraud_dataset.xlsx", index=False)

print("✅ Processed dataset saved successfully!")
print("Shape:", df.shape)

✅ Processed dataset saved successfully!
Shape: (10000, 16)

In [11]:
import os

print(os.listdir("../Data"))

['fraud_dataset.xlsx', 'processed_fraud_dataset.xlsx']